/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianHaradaMethodPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/harada.ts
var import_obsidian = require("obsidian");
var HaradaMethod = class extends import_obsidian.MarkdownRenderChild {
  constructor(containerEl, text) {
    super(containerEl);
    this.text = text;
  }
  parse() {
    let goal = "";
    const keyplans = new Array(8).fill("-");
    const actions = new Array(8);
    for (let i = 0; i < actions.length; i++) {
      actions[i] = new Array(8).fill("-");
    }
    const lines = this.text.split("\n");
    let current_keyplans_index = -1;
    let current_actions_index = -1;
    for (const line of lines) {
      const leading_space = line.match(/^(\s+)/);
      let leading_space_length = 0;
      if (leading_space != null) {
        leading_space_length = leading_space[0].length;
      }
      const level = leading_space_length / 2;
      if (Number.isInteger(level) == false) {
        break;
      }
      if (level == 0) {
        if (goal == "") {
          goal = line;
        }
      } else if (level == 1) {
        current_keyplans_index += 1;
        current_actions_index = -1;
        if (current_keyplans_index <= 8) {
          keyplans[current_keyplans_index] = line.trim();
        }
      } else if (level == 2) {
        current_actions_index += 1;
        if (current_actions_index <= 8) {
          actions[current_keyplans_index][current_actions_index] = line.trim();
        }
      }
    }
    return {
      "goal": goal,
      "keyplans": keyplans,
      "actions": actions
    };
  }
  onload() {
    var _a;
    const table = document.createElement("table");
    table.id = "harada";
    const { goal, keyplans, actions } = this.parse();
    for (let y = 0; y < 9; y++) {
      const row = document.createElement("tr");
      for (let x = 0; x < 9; x++) {
        let content = "";
        const box_index = Math.floor(x / 3) + Math.floor(y / 3) * 3;
        const inbox_index = x % 3 + y % 3 * 3;
        const cell = document.createElement("td");
        cell.classList.add("cell");
        if (y % 3 == 0) {
          cell.classList.add("top");
        }
        if (y % 3 == 2) {
          cell.classList.add("bottom");
        }
        if (x % 3 == 0) {
          cell.classList.add("left");
        }
        if (x % 3 == 2) {
          cell.classList.add("right");
        }
        if (box_index == 4 && inbox_index == 4) {
          content = goal;
          cell.classList.add("goal");
        } else if (box_index == 4) {
          let keyplan_index = inbox_index;
          if (inbox_index > 4) {
            keyplan_index = inbox_index - 1;
          }
          content = keyplans[keyplan_index];
          cell.classList.add("keyplan");
        } else if (inbox_index == 4) {
          let keyplan_index = box_index;
          if (box_index > 4) {
            keyplan_index = box_index - 1;
          }
          content = keyplans[keyplan_index];
          cell.classList.add("keyplan");
        } else {
          let keyplan_index = box_index;
          if (box_index > 4) {
            keyplan_index = box_index - 1;
          }
          let action_index = inbox_index;
          if (inbox_index > 4) {
            action_index = inbox_index - 1;
          }
          try {
            content = actions[keyplan_index][action_index];
          } catch (err) {
            console.log(err);
          }
          cell.classList.add("action");
        }
        const regex = /\[\[(.*?)\]\]/;
        const match = content.match(regex);
        if (match != null) {
          const matched_text = match[1];
          const split = matched_text.split("|");
          const path = split[0];
          let title = (_a = split[1]) != null ? _a : split[0];
          const a = cell.createEl("a");
          a.text = title;
          a.href = path;
          a.addClass("internal-link");
        } else {
          cell.textContent = content;
        }
        row.appendChild(cell);
      }
      table.appendChild(row);
    }
    this.containerEl.replaceWith(table);
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  goalBackgroundColor: "#FFE5AC",
  keyplanBackgroundColor: "#EFFFC9",
  actionBackgroundColor: "#FFFFFF",
  goalTextColor: "#000000",
  keyplanTextColor: "#000000",
  actionTextColor: "#00000"
};
var ObsidianHaradaMethodPlugin = class extends import_obsidian2.Plugin {
  async process(source, element, context) {
    context.addChild(new HaradaMethod(element, source));
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ObsidianHaradaMethodPluginSettingTab(this.app, this));
    this.registerMarkdownCodeBlockProcessor("harada", this.process);
  }
  onunload() {
  }
  async applySettings() {
    Array.from(document.getElementsByClassName("goal")).forEach((element) => {
      element.style.backgroundColor = this.settings.goalBackgroundColor;
      element.style.color = this.settings.goalTextColor;
    });
    Array.from(document.getElementsByClassName("keyplan")).forEach((element) => {
      element.style.backgroundColor = this.settings.keyplanBackgroundColor;
      element.style.color = this.settings.keyplanTextColor;
    });
    Array.from(document.getElementsByClassName("action")).forEach((element) => {
      element.style.backgroundColor = this.settings.actionBackgroundColor;
      element.style.color = this.settings.actionTextColor;
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.applySettings();
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applySettings();
  }
};
var ObsidianHaradaMethodPluginSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Colors" });
    new import_obsidian2.Setting(containerEl).setName("Goal Background Color").addColorPicker((cb) => cb.setValue(this.plugin.settings.goalBackgroundColor).onChange(async (value) => {
      this.plugin.settings.goalBackgroundColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Goal Text Color").addColorPicker((cb) => cb.setValue(this.plugin.settings.goalTextColor).onChange(async (value) => {
      this.plugin.settings.goalTextColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Keyplan Background Color").addColorPicker((cb) => cb.setValue(this.plugin.settings.keyplanBackgroundColor).onChange(async (value) => {
      this.plugin.settings.keyplanBackgroundColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Keyplan Text Color").addColorPicker((cb) => cb.setValue(this.plugin.settings.keyplanTextColor).onChange(async (value) => {
      this.plugin.settings.keyplanTextColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Action Background Color").addColorPicker((cb) => cb.setValue(this.plugin.settings.actionBackgroundColor).onChange(async (value) => {
      this.plugin.settings.actionBackgroundColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Action Text Color").addColorPicker((cb) => cb.setValue(this.plugin.settings.actionTextColor).onChange(async (value) => {
      this.plugin.settings.actionTextColor = value;
      await this.plugin.saveSettings();
    }));
  }
};

/* nosourcemap */